name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  DeployProd:
	name: Deploy to prod
	if: github.event.name == 'pull_request'
	needs: [Build]
	runs-on: ubuntu-latest
	environment: 
		name: Development 
		url: https://vikaslogistic.in

    

    
