name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  DeployProd:
    name: Deploy to Production
    if: github.event.name == 'pull_request'
    runs-on: ubuntu-latest
    environment: 
      name: Production 
      url: https://vikaslogistic.in

    

    
