on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    npmInstall:
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v2
              with:
              node-version: '12'
              check-latest: true
          - run: npm install
          - run: npm check-rules

build:
  runs-on: ubuntu-latest

  steps:

    - name: Checkout

      uses: actions/checkout@v2

    - name: Setup Node.js

      uses: actions/setup-node@v2-beta

      with:

        node-version: '12'

        check-latest: true

    - name: Install NPM dependencies

      run: npm install

    - name: Compile assets for production

      run: npm run production
